version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - setup_remote_docker
      - checkout
      - run:
            name: Install Jfrog CLI
            command: |
                curl -fL https://getcli.jfrog.io | sh 
      - run:
            name: Install and give permissions
            command: |
                curl -fL https://install-cli.jfrog.io | sh 
      - run:
            name: give per
            command: |
                chmod a+x jfrog && sudo mv jfrog /usr/local/bin  
      - run:
            name: Configure  Jfrog CLI
            command: |
              jfrog config add artifactory-server --url="https://vijaymakke.jfrog.io" --user="vijayabhaskarmakke@gmail.com" --password="Persistent@12345$" --interactive=false
      - run:
            name: Docker Build
            command: |
              docker login -u vijayabhaskarmakke@gmail.com -p Persistent@12345$ vijaymakke.jfrog.io
      - run:
            name: Docker Push to Jfrog  Registry
            command: |
              docker build . -t vijaymakke.jfrog.io/default-docker-local/vijay:1.0-${CIRCLE_BUILD_NUM}
      - run:
            name: docker jf scan
            command: |
              jf docker scan vijaymakke.jfrog.io/default-docker-local/vijay:1.0-${CIRCLE_BUILD_NUM} --watches admin
      - run:
            name: docker push
            command: |
              docker push vijaymakke.jfrog.io/default-docker-local/vijay:1.0-${CIRCLE_BUILD_NUM}
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py 

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build